bitwalker/exirc

- lib/exirc/client.ex
Prior to this commit, registering the name for an ExIrc.Client process,
it was a two-step process of `ExIrc.Client.start_link` and then
`Process.register`. This also made registering a name for
supervisor-started `ExIrc.Client` processes a bit tricky. This commit
allows end users to start `ExIrc.Client` processes from a supervisor,
but still register a name, as in the example below.
```
children = [
worker(ExIrc.Client, [[debug: true], [name: :irc_client]])
]
supervise(children, strategy: :one_for_all)
```
> Allow ExIrc.Client.start_link to use process opts

- lib/exirc/client.ex
The names list is blank when "joining" a channel, and wanted to get the names list when it was available. Not sure of the formatting of the arguments or if its a good idea or not. 
If there is a better way to do this, I'd be down for using that.
Thanks for this great IRC client =)
> Adding :names_list event on getting names list

- lib/exirc/client.ex
This way for things that are unsupported like CAP things (with twitch specifically tested), we can handle almost anything.
(In relation to this issue: https://github.com/bitwalker/exirc/issues/28)
> Send an event for unrecognized messages

- lib/exirc/client.ex
A tiny change to ` lib/exirc/client.ex`.
As of OTP 18, erlang:now() is deprecated, see the [Erlang time documentation](http://www.erlang.org/doc/apps/erts/time_correction.html#Dos_and_Donts) for more informations about this issue.
> Replace erlang.now() by the more appropriate 'timestamp'

- lib/exirc/client.ex
By blocking `NICK` before logging on finishes, the client is unable to handle `ERR_NICKNAMEINUSE` and `ERR_UNAVAILRESOURCE`. Allow `NICK` even when server hasn't sent `RPL_WELCOME` yet, so clients can pick a different nickname.
> Allow use of NICK command before RPL_WELCOME

- lib/exirc/exirc.ex
- test/client_test.exs
this allows starting multiple clients at the same time. before `{:error, :already_started}` was returned when calling `ExIrc.start_client!` twice.
> use simple one for one supervisor for clients

- lib/exirc/client.ex
irc.hackint.org was giving me an error: 409    ERR_NOORIGIN ":No origin specified", which was due to the missing server/origin.
An example ping looks like this: 
```
<< PING :F81200C8
>> PONG F81200C8 
```
While this was failing:
```
<< PING :BADC1A2C
>> PONG #{state.nick} BADC1A2C
<< :ctdo.hackint.org 409 #{state.nick} :No origin specified
```
So I had to at least change the order of the arguments passed to ping2!.
From what I understand the second parameter should rather be the target/server it should be sent to (but seems to be ignored anyway). Maybe it is for server<->server communication.
> Fix pong message

- lib/exirc/sender_info.ex
Otherwise, mix throws an error.
> Fix the module name

- lib/exirc/channels.ex
- lib/exirc/client.ex
- test/channels_test.exs
Prior to this commit ExIrc did not know what to do with QUIT messages,
which would result in nicks remaining in the `Channels` data structure
when they should not. This commit implements handling of the QUIT
message and ensures that the new `Channels.user_quit` function is called
to flush the departing user from all known channels.
Close #40
> handle QUIT messages

- lib/exirc/client.ex
- lib/exirc/exirc.ex
- test/client_test.exs
This adds two changes regarding managing connection processes:
* when a connection is started the starting process will be monitored. If that process dies, the connection will die as well
* the supervisor's type is changed to `temporary`. Since starting a connection though the supervisor does not support naming the process, restarting it makes no sense - the pid we initially received is no longer valid after process is restarted by the supervisor.
You can still name the process when starting it outside from the `:exirc` supervisor which makes perfect sense.
> Prevent zombie connections

- lib/exirc/utils.ex
- test/utils_test.exs
RFC 2812 allows all octets except `NUL`, `CR`, `LF`, `" "` and `"@"`in usernames. `ExIrc.Utils.parse_from` splits the message prefix too eagerly, breaking up the username into multiple sections, which confuses the following case clause and crashes the client.
This PR changes the split+weave into a single regex scan that extracts the prefix parts directly. Tests are included.
> Fix message prefix handling

- lib/exirc/utils.ex
- test/utils_test.exs
Hi @bitwalker!
It's a simple and probably naive attempt to fix the unicode issue in the ExIrc.Utils module.
Basically, my idea was to check for a printable charlist, in that case we use `IO.chardata_to_string/1`. If this doesn't work (incorrect unicode code points), we fallback to the unicode unsafe function `IO.iodata_to_binary/1`.
What's your view on this problem? I'll happily change/adapt my code if you do not agree with this modification :)
> Fix unicode bug when parsing message arguments

- mix.exs
This commit fixes the lint errors that Mix reports when building
ExIRC.
The errors are to do with package and deps being ambigious, and they
should be called *as* functions, not variables.
> Fix lint errors with mix

- lib/exirc/utils.ex
- test/utils_test.exs
As per the issue reported in #59, this commit fixes that issue with a
regex patch suggested by @vktec.
This commit has been tested with cloaks, and _appears_ to work, which is
a good improvement.
Because of the improvement, this fixes #59.
> Fix IRC regex handling of slashes in host

- lib/exirc/client.ex
This commit adds NOTICE handling support, as well as support for when
the client is told to to identify by NickServ, which /usually/ comes in
the form of a NOTICE. Later versions of this patch should account for
other ways NickServ might ask a client to identify.
(Related to #65)
> Add NOTICE support (and by ext, NickServ support)

- README.md
This commit meant to provide a list of projects that use ExIrc to the README.
I've added @ryanwinchester 's bot Kuma to the list, as well as my own bot Offension as well.
If there's any other bots to be added, we can add those in later commits.
WDYT?
> Add "list of projects that use ExIrc" to README

- lib/exirc/client.ex
Noticed that KICK messages didn't get handled, as reason was missing from arguments. Here's a quick fix.
> Fixed handling of KICK messages

- lib/exirc/channels.ex
- lib/exirc/client.ex
- lib/exirc/commands.ex
- lib/exirc/logger.ex
- lib/exirc/utils.ex
- lib/exirc/whois.ex
Hi @bitwalker! I have made the following changes in the code base:
* Implemented the relevant `handle_data` functions to catch the messages
* Added the numerics in `Irc.Commands`, except for `@rpl_whoismodes` that I have not encountered yet.
* Added a `whois_buffers` key in `%ClientState` to store the intermediate results.
* Added an `%Irc.Whois{}` struct to enforce the authorized keys and ensure data integrity and document the available fields.
* Updated the code to use the non-deprecated versions of `String.strip` and `String.to_char_list`.
> Implementation of Whois feature.

- lib/exirc/client.ex
- lib/exirc/commands.ex
- lib/exirc/who.ex
- lib/exirc/whois.ex
This PR adds the ability to perform and parse WHO queries on channels. Moreover, it provides fields like `operator?` and `voiced?` that may be used to build a list of ops/voiced. Those fields will expand in the future when experience and/or complaints discover more of them.
> Add WHO query

- lib/exirc/client.ex
- lib/exirc/commands.ex
- lib/exirc/who.ex
- lib/exirc/whois.ex
In an effort to keep a consistent codebase and facilitate our future work with ExIRC, I open this PR to submit an harmonization of the code regarding the use of `nick` and `nickname`.
This PR turns all occurrences of `nickname` to `nick`, as the latter being more widely used throughout the codebase.
@bitwalker 
@hrefhref 
Your opinion?
> Terminology harmonization

- examples/bot/lib/bot.ex
- lib/exirc/client.ex
- lib/exirc/example_handler.ex
Currently the login hangs if the nickname the bot tries to claim is in use. Added handling for the error server will return in this case and a callback message. The library user can then decide how to react to this, for example by dying gracefully or retrying with a different nick. It's enough to transmit a new `NICK` command to server at this point to achieve login.
I decided to namespace the login_failed message, so similar handling can be added for failed password attempt etc.
Example provided in ExampleBot how to recover and continue login with a randomized nick.
> Listen to nickname in use error when logging in

- test/client_test.exs
I noticed there are hardly any tests for the client code. I was thinking about how to test genservers in Elixir and this is what I came up with. I call `handle_data` and expect a message to the handler process, which is actually the ExUnit process itself.
I'm open for discussion. Does this make any sense? Are there better conventions for testing in Elixir?
> Add a few client tests

- .github/workflows/tests.yaml
This PR adds support for GitHub actions, adding automated testing.
> Add a GitHub action for automated testing
